VALHEIM="valheim"
#name to use for running server container

#Docker images
##############
STEAM="docker.io/steamcmd/steamcmd:latest"
#image for steamcmd

UBUNTU="docker.io/ubuntu:latest"
#image used to run server
#ubuntu was my prefence, but you could easily use another image such as debian or centos

#Server Data
############
LOCAL_DATA="/disk2/steamcmd"
#where to store your game files
#IMO it is more practical to mount the game files into a container then to copy them into a image

REMOTE_DATA="/app"
#where in the container to mount the game files
#if you change this, update force_install_dir variable in config/update_script.conf

INSTALL_DIR="$REMOTE_DATA/valheim_standalone"


#if you change REMOTE_DATA or INTALL_DIR, update force_install_dir variable in config/update_script.conf
