#!/bin/bash

FROM docker.io/ubuntu:latest

LABEL ogrydziak.net.release-date="2021-02-12"

RUN apt-get -y update && \
  apt-get -y upgrade

COPY ./config/valheim_start_script.sh /etc/valheim_start_script.sh

EXPOSE 2456-2458/udp

ENTRYPOINT ["/etc/valheim_start_script.sh"]
